name: Scan session
description: log session
title: "[SCAN] sub-xx_ses-yyy"
labels: [scan]
assignees: 
  - bpinsard
body:
- type: markdown
  attributes:
    value: "# general infos"

- type: checkboxes
  id: setup
  attributes:
    label: Setup
    description: check all the equipment that was set up
    options:
      - label: biopac
      - label: sensimetrics
      - label: eyetracker
      - label: game controller

- type: textarea
  attributes:
    label: general notes

- type: markdown
  attributes:
    value: "## task-dms_run-01"
- type: checkboxes
  attributes:
    label: task-dms_run-01 completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-dms_run-01 issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-dms_run-01 notes

- type: markdown
  attributes:
    value: "## task-interdms_run-01"
- type: checkboxes
  attributes:
    label: task-interdms_run-01 completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-interdms_run-01 issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-interdms_run-01 notes

- type: markdown
  attributes:
    value: "## task-interdms_run-02"
- type: checkboxes
  attributes:
    label: task-interdms_run-02 completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-interdms_run-02 issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-interdms_run-02 notes



- type: markdown
  attributes:
    value: "## task-interdms_run-03"
- type: checkboxes
  attributes:
    label: task-interdms_run-03 completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-interdms_run-03 issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-interdms_run-03 notes

- type: markdown
  attributes:
    value: "## task-ctxdm_run-01"
- type: checkboxes
  attributes:
    label: task-ctxdm_run-01 completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-ctxdm_run-01 issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-ctxdm_run-01 notes

- type: markdown
  attributes:
    value: "## task-nback_run-01"
- type: checkboxes
  attributes:
    label: task-nback_run-01 completion  
    options:
      - label: series was completed.
- type: dropdown
  attributes:
    label: task-nback_run-01 issues
    multiple: true
    options:
      - sleep
      - excessive motion
      - eyetracking issues (crash, pupil loss)
      - physio signal quality issue
      - controller issues
- type: textarea
  attributes:
    label: task-nback_run-01 notes
